spring.application.name=ProGig

spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.jpa.properties.hibernate.format_sql=true

springdoc.swagger-ui.disable-swagger-default-url=true
spring.profiles.active=${ENV:dev}
server.address=0.0.0.0
server.port=${PORT:8080}

jwt.secret=${JWT_SECRET:08a92ff4ce98dbdd138103ec96eb62af58ff358317b0ade6ad944042137b0e11}
cors.allowed-origins=${CORS_ORIGINS:http://localhost:5173,http://localhost:3000}